name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (or other environment)
      - name: sample
        run: echo "Hello, world!"

      - name: Intentionally fail the workflow
        uses: jwalton/gh-fail@v1
        with:
        error-message: "This action will fail the workflow intentionally."
